Document: spark-spl
Title: Debian spark-spl Manual
Author: <insert document author here>
Abstract: This manual describes what spark-spl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spark-spl/spark-spl.sgml.gz

Format: postscript
Files: /usr/share/doc/spark-spl/spark-spl.ps.gz

Format: text
Files: /usr/share/doc/spark-spl/spark-spl.text.gz

Format: HTML
Index: /usr/share/doc/spark-spl/html/index.html
Files: /usr/share/doc/spark-spl/html/*.html
